### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by Aviatims** [mdolab/pyspline#43]
Hello,

I have tried to install pyspline on my windows notebook, but when I run the script for a FFD mesh, I get the following error message: ImportError: cannot import name 'libspline' from partially initialized module 'pyspline' (most likely due to a circular import) (C:\Users\timsc\AppData\Local\Continuum\anaconda3\envs\suave\lib\site-packages\pyspline\__init__.py)

I was not sure about the installation procedure provided on th website: https://mdolab-pyspline.readthedocs-hosted.com/en/latest/building.html

Is this not designed for windows, or can I neglect the first steps of building the fortran library (I assume that this is where the error lies)?

All the best!

**Comment by bernardopacini** [comment]
The Fortran installation is required for pySpline, without it the code is missing its core. We do not support Windows, please review the installation guide for supported operating systems and requirements.

**Comment by Aviatims** [comment]
Thank you for your fast response! I was already suspecting this. Unfortunately I couldn't see in the installation guide (https://mdolab-pyspline.readthedocs-hosted.com/en/latest/building.html) which version is supported, but assumed windows was not supported..

Is it then not possible to run PyGeo on windows as it requires PySpline? I need PyGeo to use the FFD mesh feature in OpenAeroStruct.

**Comment by nwu63** [comment]
Yeah we can probably update the docs. pySpline belongs to a group of packages we call MACH with installation instructions [here](https://mdolab-mach-aero.readthedocs-hosted.com/en/latest/installInstructions/installFromScratch.html). pySpline is rarely used outside of that context and its integration with OAS is not supported beyond Linux. As you said, WSL is probably your best bet. At the moment we primarily support Linux since that's the OS we all use internally.
